pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                sh '/usr/bin/terraform init'
            }
        }
        stage('Plan') {
            steps {
                sh '/usr/bin/terraform plan'
            }
        }
        stage('Apply') {
            steps {
                script {
                    def userInput = input(
                        id: 'userInput', message: 'Soll die Änderung angewendet werden?', parameters: [
                        booleanParam(name: 'APPLY', defaultValue: false, description: 'Apply Terraform changes?')
                    ])
                    if (userInput == 'true') {
                        sh '/usr/bin/terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}

